# Generated by Django 3.0.4 on 2020-05-01 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('gallery', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='my_users',
        ),
    ]
